INSERT INTO CLIENTES(nombre, apellido, dni) VALUES('RUBEN', 'FLORES', '41975678');
INSERT INTO CLIENTES(nombre, apellido, dni) VALUES('JUAN', 'GALVEZ', '42756785');
INSERT INTO CLIENTES(nombre, apellido, dni) VALUES('DIANA', 'VIDAL', '43756781');
INSERT INTO CLIENTES(nombre, apellido, dni) VALUES('JAIME', 'ALDAVE', '44897567');
INSERT INTO CLIENTES(nombre, apellido, dni) VALUES('ALEX', 'LOAYZA', '45975678');

INSERT INTO MONEDAS(TIPOMONEDA) VALUES('SOL');
INSERT INTO MONEDAS(TIPOMONEDA) VALUES('DOLAR');

INSERT INTO TARJETAS(tipotarjeta, FK_MONEDA, FK_CLIENTE) VALUES('CLASICA', 1, 1);
INSERT INTO TARJETAS(tipotarjeta, FK_MONEDA, FK_CLIENTE) VALUES('ORO', 1, 2);
INSERT INTO TARJETAS(tipotarjeta, FK_MONEDA, FK_CLIENTE) VALUES('BLACK', 2,3);
INSERT INTO TARJETAS(tipotarjeta, FK_MONEDA, FK_CLIENTE) VALUES('CLASICA', 1, 4);
INSERT INTO TARJETAS(tipotarjeta, FK_MONEDA, FK_CLIENTE) VALUES('ORO', 1, 5);





